name: mcnenv
channels:
  - conda-forge
  - defaults
dependencies:
  - pytorch=2.5.1
  - tqdm
  - pip
  - matplotlib
  - numpy=2.1.3
  - python=3.12.12
  - trimesh
  - cython=3.0.8
  - open3d
prefix: /opt/miniconda3/envs/mcnenv
