name: mcnenv
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - cython=3.0.8
  - numpy=2.1.3
  - pip
  - python=3.12.2
  - pytorch=2.5.1
  - matplotlib
  - tqdm
  - trimesh
prefix: /home/riella/anaconda3/envs/mcnenv
